name = "lifeguesser"
compatibility_date = "2024-09-01"
pages_build_output_dir = "./dist"

[[kv_namespaces]]
binding = "LIFEGUESSER_KV"
id = "d316800fcf0d44adb448495e90f5c0e4"

# Enable after confirming the cron schedule in the Cloudflare dashboard.
# [triggers]
# crons = ["0 */6 * * *"]   # every 6 hours

[[d1_databases]]
binding = "DB"
database_name = "lifeguesser-db"
database_id = "05b767b8-d699-4059-bb15-4e412cdb9949"
