name = "lifeguesser"
account_id = "6f713a483248b6f86e97dc60bcac7d60"
compatibility_date = "2024-09-01"
pages_build_output_dir = "./dist"

[[kv_namespaces]]
binding = "LIFEGUESSER_KV"
id = "d316800fcf0d44adb448495e90f5c0e4"

# Enable after confirming the cron schedule in the Cloudflare dashboard.
# [triggers]
# crons = ["0 */6 * * *"]   # every 6 hours

[[d1_databases]]
binding = "DB"
database_name = "lifeguesser"
database_id = "69a641ce-0063-46f5-9210-23dbca80d835"
